DATASET:
  TYPE: 'SD'
  PATH: '../../depth_data/phoenix/S6/zl548/MegaDepth_v1/0012/dense0/'

DATA:
  MIN_DEPTH: 0.01
  MAX_DEPTH: 80.0 #Check
  NORMALIZE_MEAN: [0.0,0.0,0.0]
  NORMALIZE_STD: [0.229, 0.224, 0.225]
  TRAIN_CROP_SIZE: [512,512]
  CENTER_CROP_SIZE: [512,512]

  